function names = TTLinfo_colNames()
% Return the list of TTLinfo column names
names = { ...
    'Time', ...
    '2', ...
    'Events', ...
    'ShockOBSCTLStim', ...
    'ShockTailStim', ...
    'AdjustPDItime', ...
    '7', ...
    '8', ...
    '9', ...
    'VisualStim', ...
    'AuditoryStim', ...
    'Shock', ...
    '13' ...
};
end
